### ISSUE TITLE
在IE7、8下面使用table生成，但是设置的宽度和高度无效

### ISSUE THREAD

**Issue by aofong** [aralejs/qrcode#12]

**Comment by Nuintun** [comment]
二维码有多个version，例如 version 1 的二维码是 21 * 21 的矩阵，当你设定宽度和高度小于21的时候，就会出现td的宽高不足1px的情况，只能把td的宽度重置成 1，用table生成的二维码，宽度大部分都不是你设定的大小！

**Comment by lizzie** [comment]
楼上正解。IE67就表追求完美了。
