### ISSUE TITLE
对浏览器的支持如何？尤其低端浏览器，比如IE6，7，8。手机浏览器呢？

### ISSUE THREAD

**Issue by longmonhau** [aralejs/qrcode#13]

**Comment by Nuintun** [comment]
手机支持没问题，ie 6， 7， 8 也是支持的，但是 ie 6， 7， 8 使用table来生成的，在二维码数据比较大的情况下，速度就不敢恭维了，你可以去 http://nuintun.github.io/qrcode/examples/qrcode.html 测试！

**Comment by lizzie** [comment]
被此二维码坑了， IE67 的，110px尺寸的还可以，小尺寸的，如80px的，会自动缩小成50px左右。且，变小之后，很难扫出来。

试了 @Nuintun 的。根据色块大小来的，最小的1，生成后也能扫出来。但是就不能调节整体二维码的大小。

前端绘制二维码的终极解决方案：`IE67 小尺寸的二维码索性隐藏`
