### ISSUE TITLE
还依赖seajs，是吗？

### ISSUE THREAD

**Issue by think2011** [aralejs/qrcode#14]
我只找到src/下的文件，但是不知道2个文件代表什么。

然后发现还依赖seajs，我的项目并没有seajs，而且不打算用，挺困惑的。

**Comment by afc163** [comment]
不要用这个了。可以用 https://github.com/jeromeetienne/jquery-qrcode 或 https://github.com/davidshimjs/qrcodejs

**Comment by lizzie** [comment]
@afc163 贴的两个链接，前一个兼容性不好，IE678，编码较长的内容，size<100px的时候，生成的二维码是变形的 汗~ 到目前为止没找到一个靠谱的二维码组件。。

**Comment by think2011** [comment]
@afc163  选择了第二个，谢谢！

**Comment by nimojs** [comment]
@afc163  为什么不要用这个了？这个不是基于 SPM3  CommonJS 构建么？
