### ISSUE TITLE
生成的二维码是否可以使image,因为这些image我要下载下来用

### ISSUE THREAD

**Issue by gaoguoxin** [aralejs/qrcode#9]
如题，想知道是否可以将生成的二维码转换为image，然后可以下载下来，看了很多都是直接生成svg或者canvas，虽说也可以下载保存为image，但是我的下载是通过程序下载(比如爬虫)

**Comment by Nuintun** [comment]
可以自己用toDataURL转换成想要的图片，但是低版本浏览器不支持！
